language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx

addons:
  apt:
    packages:
      - cmake
      - swig
      - libasound2-dev
      - libunittest++-dev
      - doxygen
      - graphviz

before_install:
  - pwd
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update
      brew install swig unittest-cpp doxygen
    fi

script:
  - mkdir -p build; cd build;
  - cmake -DCMAKE_INSTALL_PREFIX:PATH="$TRAVIS_OS_NAME-x64" -DCMAKE_BUILD_TYPE:STRING="Debug" ../
  - make VERBOSE=1
  - make doc
  - make install

notifications:
  email: true

env:
  global:
  - TRAVIS_LIBOPENSHOT=TEST
  - LANG="en_US.UTF-8"
